#!/usr/bin/env bash
echo "-------------------------"
echo "START BUILDING DH-THESIS"
echo "-------------------------"
echo ""
echo "CLONE REPOSITORIES"
echo ""
mkdir dh-thesis
cd dh-thesis
git clone https://github.com/dh-thesis/crawl.git
git clone https://github.com/dh-thesis/retrieve.git
echo ""
echo "PREPARE RETRIEVAL"
echo ""
cd retrieve/
virtualenv -p python3 --no-site-packages env
source env/bin/activate
pip install -r requirements.txt
deactivate
./main
echo ""
echo "RETRIEVAL DONE!"
echo ""
echo ""
echo "PREPARE CRAWL"
echo ""
cd ../crawl
virtualenv -p python3 --no-site-packages env
source env/bin/activate
pip install -r requirements.txt
deactivate
./main
echo ""
echo "CRAWL DONE!"
echo ""
